"""Visible signature appearance composition for DSC signatures.

Produces a single-page PDF (sized exactly to the target signature-field box, in
PDF points) that is used as the pyHanko *static* stamp appearance for the
cryptographic signature. Because the appearance is generated by ReportLab as a
PDF page (not a raster), text is rendered with the built-in Helvetica font — no
external TrueType font files are required, which keeps the library portable
across hosts and container images.

Layout (DocuSign + DSC hybrid, per product decision):

    +-------------------------------------------------------------+
    |  <handwritten signature image>  |  Digitally signed by      |
    |                                 |  <SUBJECT CN>             |
    |                                 |  Date: 2026.07.26 ...     |
    |                                 |  Reason: <reason>         |
    +-------------------------------------------------------------+

When no handwritten image is supplied the text block spans the full width and a
small seal glyph is drawn on the left.

This module is intentionally free of any web/DB imports so it stays reusable by
any host embedding :mod:`dsc_signing`.
"""
from __future__ import annotations

import io
import os
import tempfile
from typing import Optional


# Brand-neutral, professional palette (RGB 0-1). Hosts may restyle by editing
# these constants or by supplying their own appearance PDF path to the flow.
_INK = (0.12, 0.16, 0.22)          # near-slate-900 text
_MUTED = (0.42, 0.47, 0.53)        # slate-500 labels
_ACCENT = (0.03, 0.57, 0.70)       # teal-600 accent / divider
_BORDER = (0.80, 0.84, 0.88)       # slate-200 border


def _clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


def _fit_lines(text: str, max_chars: int) -> str:
    text = (text or "").strip()
    if len(text) <= max_chars:
        return text
    return text[: max(1, max_chars - 1)].rstrip() + "\u2026"


def render_appearance_pdf(
    box_w_pt: float,
    box_h_pt: float,
    *,
    subject_cn: Optional[str],
    signed_time_str: str,
    reason: Optional[str] = None,
    location: Optional[str] = None,
    handwritten_png: Optional[bytes] = None,
    out_path: Optional[str] = None,
) -> str:
    """Render the visible signature appearance to a one-page PDF.

    :param box_w_pt: field width in PDF points.
    :param box_h_pt: field height in PDF points.
    :param subject_cn: certificate subject common name (the signer).
    :param signed_time_str: pre-formatted signing time (Adobe-style recommended).
    :param reason: optional reason string.
    :param location: optional location string.
    :param handwritten_png: optional handwritten signature image (PNG/JPEG bytes).
    :param out_path: optional output path; a temp file is created when omitted.
    :returns: path to the generated single-page PDF (caller owns cleanup).
    """
    from reportlab.pdfgen import canvas
    from reportlab.lib.utils import ImageReader

    w = max(24.0, float(box_w_pt))
    h = max(14.0, float(box_h_pt))

    if out_path is None:
        fd, out_path = tempfile.mkstemp(suffix="_dsc_appearance.pdf")
        os.close(fd)

    c = canvas.Canvas(out_path, pagesize=(w, h))

    # Outer border (subtle, rounded feel via thin stroke).
    c.setLineWidth(0.6)
    c.setStrokeColorRGB(*_BORDER)
    c.rect(0.5, 0.5, w - 1.0, h - 1.0, stroke=1, fill=0)

    pad = _clamp(h * 0.10, 2.0, 6.0)
    has_img = bool(handwritten_png)
    img_region_w = (w * 0.44) if has_img else (h * 0.9)
    text_x = (img_region_w + pad * 1.5) if has_img else (h * 0.9 + pad)

    # ── Left: handwritten image or seal glyph ────────────────────────────────
    if has_img:
        try:
            reader = ImageReader(io.BytesIO(handwritten_png))
            iw, ih = reader.getSize()
            avail_w = img_region_w - pad
            avail_h = h - pad * 2
            scale = min(avail_w / iw, avail_h / ih) if iw and ih else 1.0
            draw_w = iw * scale
            draw_h = ih * scale
            dx = pad + (avail_w - draw_w) / 2.0
            dy = (h - draw_h) / 2.0
            c.drawImage(reader, dx, dy, width=draw_w, height=draw_h,
                        mask="auto", preserveAspectRatio=True)
        except Exception:
            has_img = False  # fall back to text-only layout below

        # Vertical divider between image and text.
        c.setStrokeColorRGB(*_ACCENT)
        c.setLineWidth(0.8)
        div_x = img_region_w + pad * 0.5
        c.line(div_x, pad, div_x, h - pad)
        text_x = div_x + pad
    else:
        # Simple seal/lock glyph drawn with primitives (font-independent).
        cx = pad + (h * 0.9) / 2.0
        cy = h / 2.0
        r = _clamp(min(h, w) * 0.28, 5.0, 16.0)
        c.setStrokeColorRGB(*_ACCENT)
        c.setFillColorRGB(*_ACCENT)
        c.setLineWidth(1.2)
        c.circle(cx, cy, r, stroke=1, fill=0)
        # lock body
        c.rect(cx - r * 0.45, cy - r * 0.55, r * 0.9, r * 0.7, stroke=0, fill=1)
        # shackle
        c.setLineWidth(1.0)
        c.arc(cx - r * 0.30, cy - r * 0.05, cx + r * 0.30, cy + r * 0.55,
              startAng=0, extent=180)

    # ── Right: certificate text block ────────────────────────────────────────
    avail_text_w = w - text_x - pad
    # Approximate max chars per line for Helvetica (avg ~0.5em width).
    def _max_chars(font_size: float) -> int:
        return max(6, int(avail_text_w / (font_size * 0.5)))

    label_size = _clamp(h * 0.13, 5.0, 8.0)
    cn_size = _clamp(h * 0.20, 6.5, 12.0)
    meta_size = _clamp(h * 0.12, 5.0, 8.0)
    line_gap = _clamp(h * 0.06, 1.0, 4.0)

    y = h - pad - label_size

    c.setFillColorRGB(*_MUTED)
    c.setFont("Helvetica", label_size)
    c.drawString(text_x, y, "Digitally signed by")
    y -= (cn_size + line_gap)

    c.setFillColorRGB(*_INK)
    c.setFont("Helvetica-Bold", cn_size)
    c.drawString(text_x, y, _fit_lines(subject_cn or "DSC Signer", _max_chars(cn_size)))
    y -= (meta_size + line_gap)

    c.setFillColorRGB(*_MUTED)
    c.setFont("Helvetica", meta_size)
    if signed_time_str:
        c.drawString(text_x, y, _fit_lines(f"Date: {signed_time_str}", _max_chars(meta_size)))
        y -= (meta_size + line_gap)
    if reason and y > pad:
        c.drawString(text_x, y, _fit_lines(f"Reason: {reason}", _max_chars(meta_size)))
        y -= (meta_size + line_gap)
    if location and y > pad:
        c.drawString(text_x, y, _fit_lines(f"Location: {location}", _max_chars(meta_size)))

    c.showPage()
    c.save()
    return out_path
